name: Generate Keystore
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
    - name: Generate
      run: |
        keytool -genkeypair -v -keystore block-burst-release.keystore -alias block-burst -keyalg RSA -keysize 2048 -validity 10000 -storepass BlockBurst2026 -keypass BlockBurst2026 -dname "CN=Block Burst, OU=Dev, O=DevLance, L=India, ST=India, C=IN"
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: keystore
        path: block-burst-release.keystore
