name: Generate PEPK ZIP
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
    - name: Generate Output ZIP
      run: |
        echo -e "BlockBurst2026\nBlockBurst2026" | java -jar android/pepk.jar --keystore=android/block-burst-release.keystore --alias=block-burst --output=output.zip --include-cert --rsa-aes-encryption --encryption-key-path=android/encryption_public_key.pem
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: outputzip
        path: output.zip
